export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const LOAD_CURRENT_USER_DATA = 'LOAD_CURRENT_USER_DATA';
export const CLEAR_CURRENT_USER_DATA = 'CLEAR_CURRENT_USER_DATA';
